eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/payment/doPayment
        appname: payment-service
        path: /payment
        name: /doPayment
  
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/bookOrder
        appname: order-service
        path: /order
        name: /bookOrder
